#!/usr/bin/env python

import argparse

from stercus import preprocessor, lexer, parser, compiler

def stercus_compile(src):
    src = preprocessor.preprocess(src)
    src = lexer.lex(src)
    src = parser.parse(src)
    src = compiler.compile(src)
    return src

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('src', help='Stercus source file.')
    parser.add_argument('-o', '--output', help='Output file for lexed tokens',
                        dest='out')
    args = parser.parse_args()

    with open(args.src, 'r') as f:
        src = f.read()

    src = stercus_compile(src)

    if args.out:
        out_file = args.out
    else:
        out_file = args.src.rpartition('.')[0] + '.c'
    with open(out_file, 'w') as f:
        f.write(src)

if __name__ == '__main__':
    main()
